item = input()
price = int(input())
weight = int(input())
payment = int(input())
print("Чек")
print(f"{item} - {weight}кг - {price}руб/кг")
print(f"Итого: {price * weight}руб")
print(f"Внесено: {payment}руб")
print(f"Сдача: {payment - price * weight}руб")
