product = input()
price = int(input())
weight = int(input())
payment = int(input())
print(f"{'Чек':=^35}")
print("Товар:", f"{product: >28}")
print("Цена:", f"{f'{weight}кг * {price}руб/кг': >29}")
print("Итого:", f"{weight * price: >25}руб")
print("Внесено:", f"{payment: >23}руб")
print("Сдача:", f"{payment - weight * price: >25}руб")
print("=" * 35)
